### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mfarina1**
Updated the ACE Readme to include error resolution strategies for installation process. I may also need to add the suggestion and steps for operating in a Python virtual environment

### CODE REVIEW

**Comment by mfarina1** [comment]
Not sure why flake8 is failing and the test and release unit tests are being skipped since these are just Readme changes

**Review by BrianSipos — COMMENTED** [review]
The tests were failing because of the submodule path (repo was renamed). There is still an issue about how to handle the forked repos because the fork `main` branch is locked to act as a mirror for the upstream (fork source) main branch. Do we want to decouple the two main branches? Meaning will the ANMS repo become archived (frozen) at this point and this repo is the proper main branch?

**Comment by mfarina1** [comment]
so it's not possible to merge this branch into `main` (and update the "official" Readme for this repo) without archiving the ANMS ACE repo?

**Review by BrianSipos — APPROVED** [review]
It would be good to make the same kinds of CI workflow updates to CAMP repo on its next PR.

**Pull request merged**
